apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yml
- service_canary.yml
- ingress.yml
images:
- name: nextjs-example-rollout-canary-image
  newName: chagchagchag/nextjs-argocd-example
  newTag: "v0.0.2"
namespace: nextjs-example
