apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yml
- service_active.yml
- service_preview.yml
- ingress_active.yml
- ingress_preview.yml
images:
- name: nextjs-example-rollout-bluegreen-image
  newName: chagchagchag/nextjs-argocd-example
  newTag: "v0.0.2"
namespace: nextjs-example
