apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ./deployment.yml
#   - path: ./configmap.yml
#   - path: ./pvc.yml
#   - path: ./service.yml
resources:
- ../base
images:
- newName: chagchagchag/nextjs-argocd-example
- name: chagchagchag/nextjs-argocd-example
- name: nextjs-argocd-example-image
  newName: chagchagchag/nextjs-argocd-example
  newTag: "20240119.065920"
namespace: nextjs-example
