apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ./deployment.yml
#   - path: ./configmap.yml
#   - path: ./pvc.yml
#   - path: ./service.yml
resources:
  - ../base
images:
  - name: chagchagchag/nextjs-argocd-example
  - newName: chagchagchag/nextjs-argocd-example
  - newTag: v0.0.1
namespace: nextjs-example